// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:8edcdd2a-2b58-462f-b5d2-ddd9a361c50b",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_pwcl4qFOd",
    "aws_user_pools_web_client_id": "m8lmq1sh89pbgg1f3leqncvmn",
    "oauth": {
        "domain": "pedalobbyauth-production.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": process.env.REACT_APP_REDIRECT_AFTER_SIGN_IN,
        "redirectSignOut": process.env.REACT_APP_REDIRECT_AFTER_SIGN_OUT,
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"
}

export default awsmobile
