name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
  
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1.4.1
      with:
        node-version: 12.x
    - uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    # Runs a single command using the runners shell
    - name: Install deps
      run: npm install

    # Runs a set of commands using the runners shell
    - name: Build project
      run: npm run build
      env: 
        REACT_APP_API_HOSTNAME: https://immense-taiga-57223.herokuapp.com/graphql
        REACT_APP_REDIRECT_AFTER_SIGN_IN=https://pedais.surge.sh/
        REACT_APP_REDIRECT_AFTER_SIGN_OUT=https://pedais.surge.sh/
  
    - name: Prepare for surge
      run: cp ./build/index.html ./build/200.html
      
    - name: Deploy to pedais.surge.sh
      uses: dswistowski/surge-sh-action@v1
      with:
        domain: 'pedais.surge.sh'
        project: 'build'
        login: ${{ secrets.surge_login }}
        token: ${{ secrets.surge_token }}
      
